import Head from 'next/head'
import Image from 'next/image'
import QuoteCard from '../Components/QuoteCard/QuoteCard';
import styles from '../styles/Home.module.css'

export default function Home() {
  // const colors = [];
  const bgColor = "bg-slate-600";

  return (
    <div className={`w-[100vw] h-[100vh] flex justify-center items-center ${bgColor}`}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <QuoteCard bgColor={bgColor} />
    </div>
  )
}
