import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react';
import QuoteCard from '../Components/QuoteCard/QuoteCard';
import styles from '../styles/Home.module.css'
import { FaInfoCircle } from "react-icons/fa";


export default function Home() {
  const [bgColor, setBgColor] = useState("#59d1f7");

  return (
    <div style={{ backgroundColor: `${bgColor}` }} className={`w-[100vw] h-[100vh] relative flex justify-center items-center`}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='absolute right-[5vw] top-[5vh] cursor-pointer text-3xl'><FaInfoCircle /></div>
      <QuoteCard setBgColor={setBgColor} bgColor={bgColor} />
    </div>
  )
}
